version: '3'

volumes:
  logs:

services:
  app:
    build: .
    command: depthMeasurements.txt
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
      OTEL_SERVICE_NAME: com.andrewshawcare.advent_of_code
      OTEL_RESOURCE_ATTRIBUTES: job=app
    volumes:
      - logs:/var/log/app