defaults:
  run:
    working-directory: 2022-12-01
on:
  push:
    paths:
      - '.github/workflows/2022-12-01.yml'
      - '2022-12-01/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: 2022-12-01/.java-version
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false
      - run: build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: 2022-12-01/.java-version
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false
      - run: test
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version-file: 2022-12-01/.java-version
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          cache-read-only: false
      - run: jib
